services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
            - __pycache__/
            - .mypy_cache/
            - .ruff_cache/
        - action: rebuild
          path: ./uv.lock